/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DisruptionsResponse } from '../models';
/**
 * DisruptionsApi - axios parameter creator
 */
export const DisruptionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get a list of disruptions. Can be filtered by since/until dates.
         * @summary List disruptions
         * @param {string} coverage Coverage area (e.g., \&#39;sncf\&#39;)
         * @param {string} [since] Filter disruptions since this datetime (YYYYMMDDTHHmmss)
         * @param {string} [until] Filter disruptions until this datetime (YYYYMMDDTHHmmss)
         * @param {number} [depth] Depth of detail in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coverageCoverageDisruptionsGet: async (coverage: string, since?: string, until?: string, depth?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'coverage' is not null or undefined
            assertParamExists('coverageCoverageDisruptionsGet', 'coverage', coverage)
            const localVarPath = `/coverage/{coverage}/disruptions`
                .replace(`{${"coverage"}}`, encodeURIComponent(String(coverage)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (since !== undefined) {
                localVarQueryParameter['since'] = since;
            }

            if (until !== undefined) {
                localVarQueryParameter['until'] = until;
            }

            if (depth !== undefined) {
                localVarQueryParameter['depth'] = depth;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DisruptionsApi - functional programming interface
 */
export const DisruptionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DisruptionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get a list of disruptions. Can be filtered by since/until dates.
         * @summary List disruptions
         * @param {string} coverage Coverage area (e.g., \&#39;sncf\&#39;)
         * @param {string} [since] Filter disruptions since this datetime (YYYYMMDDTHHmmss)
         * @param {string} [until] Filter disruptions until this datetime (YYYYMMDDTHHmmss)
         * @param {number} [depth] Depth of detail in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coverageCoverageDisruptionsGet(coverage: string, since?: string, until?: string, depth?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DisruptionsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coverageCoverageDisruptionsGet(coverage, since, until, depth, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DisruptionsApi.coverageCoverageDisruptionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DisruptionsApi - factory interface
 */
export const DisruptionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DisruptionsApiFp(configuration)
    return {
        /**
         * Get a list of disruptions. Can be filtered by since/until dates.
         * @summary List disruptions
         * @param {string} coverage Coverage area (e.g., \&#39;sncf\&#39;)
         * @param {string} [since] Filter disruptions since this datetime (YYYYMMDDTHHmmss)
         * @param {string} [until] Filter disruptions until this datetime (YYYYMMDDTHHmmss)
         * @param {number} [depth] Depth of detail in response
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coverageCoverageDisruptionsGet(coverage: string, since?: string, until?: string, depth?: number, options?: RawAxiosRequestConfig): AxiosPromise<DisruptionsResponse> {
            return localVarFp.coverageCoverageDisruptionsGet(coverage, since, until, depth, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DisruptionsApi - interface
 */
export interface DisruptionsApiInterface {
    /**
     * Get a list of disruptions. Can be filtered by since/until dates.
     * @summary List disruptions
     * @param {string} coverage Coverage area (e.g., \&#39;sncf\&#39;)
     * @param {string} [since] Filter disruptions since this datetime (YYYYMMDDTHHmmss)
     * @param {string} [until] Filter disruptions until this datetime (YYYYMMDDTHHmmss)
     * @param {number} [depth] Depth of detail in response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    coverageCoverageDisruptionsGet(coverage: string, since?: string, until?: string, depth?: number, options?: RawAxiosRequestConfig): AxiosPromise<DisruptionsResponse>;

}

/**
 * DisruptionsApi - object-oriented interface
 */
export class DisruptionsApi extends BaseAPI implements DisruptionsApiInterface {
    /**
     * Get a list of disruptions. Can be filtered by since/until dates.
     * @summary List disruptions
     * @param {string} coverage Coverage area (e.g., \&#39;sncf\&#39;)
     * @param {string} [since] Filter disruptions since this datetime (YYYYMMDDTHHmmss)
     * @param {string} [until] Filter disruptions until this datetime (YYYYMMDDTHHmmss)
     * @param {number} [depth] Depth of detail in response
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public coverageCoverageDisruptionsGet(coverage: string, since?: string, until?: string, depth?: number, options?: RawAxiosRequestConfig) {
        return DisruptionsApiFp(this.configuration).coverageCoverageDisruptionsGet(coverage, since, until, depth, options).then((request) => request(this.axios, this.basePath));
    }
}

