/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '@/client/configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '@/client/common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '@/client/base';
// @ts-ignore
import type { CoordsResponse } from '@/client/models';
/**
 * InvertedGeocodingApi - axios parameter creator
 */
export const InvertedGeocodingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Given coordinates, returns the detailed postal address and the Navitia coverage regions that contain these coordinates. The coordinate format is \'lon;lat\' (longitude;latitude).
         * @summary Inverted geocoding - get address and coverage regions from coordinates
         * @param {string} coord Coordinates in format \&#39;lon;lat\&#39; (longitude;latitude), e.g., \&#39;2.37705;48.84675\&#39;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coordsCoordGet: async (coord: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'coord' is not null or undefined
            assertParamExists('coordsCoordGet', 'coord', coord)
            const localVarPath = `/coords/{coord}`
                .replace(`{${"coord"}}`, encodeURIComponent(String(coord)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvertedGeocodingApi - functional programming interface
 */
export const InvertedGeocodingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InvertedGeocodingApiAxiosParamCreator(configuration)
    return {
        /**
         * Given coordinates, returns the detailed postal address and the Navitia coverage regions that contain these coordinates. The coordinate format is \'lon;lat\' (longitude;latitude).
         * @summary Inverted geocoding - get address and coverage regions from coordinates
         * @param {string} coord Coordinates in format \&#39;lon;lat\&#39; (longitude;latitude), e.g., \&#39;2.37705;48.84675\&#39;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coordsCoordGet(coord: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoordsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coordsCoordGet(coord, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvertedGeocodingApi.coordsCoordGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InvertedGeocodingApi - factory interface
 */
export const InvertedGeocodingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InvertedGeocodingApiFp(configuration)
    return {
        /**
         * Given coordinates, returns the detailed postal address and the Navitia coverage regions that contain these coordinates. The coordinate format is \'lon;lat\' (longitude;latitude).
         * @summary Inverted geocoding - get address and coverage regions from coordinates
         * @param {string} coord Coordinates in format \&#39;lon;lat\&#39; (longitude;latitude), e.g., \&#39;2.37705;48.84675\&#39;
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coordsCoordGet(coord: string, options?: RawAxiosRequestConfig): AxiosPromise<CoordsResponse> {
            return localVarFp.coordsCoordGet(coord, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InvertedGeocodingApi - interface
 */
export interface InvertedGeocodingApiInterface {
    /**
     * Given coordinates, returns the detailed postal address and the Navitia coverage regions that contain these coordinates. The coordinate format is \'lon;lat\' (longitude;latitude).
     * @summary Inverted geocoding - get address and coverage regions from coordinates
     * @param {string} coord Coordinates in format \&#39;lon;lat\&#39; (longitude;latitude), e.g., \&#39;2.37705;48.84675\&#39;
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    coordsCoordGet(coord: string, options?: RawAxiosRequestConfig): AxiosPromise<CoordsResponse>;

}

/**
 * InvertedGeocodingApi - object-oriented interface
 */
export class InvertedGeocodingApi extends BaseAPI implements InvertedGeocodingApiInterface {
    /**
     * Given coordinates, returns the detailed postal address and the Navitia coverage regions that contain these coordinates. The coordinate format is \'lon;lat\' (longitude;latitude).
     * @summary Inverted geocoding - get address and coverage regions from coordinates
     * @param {string} coord Coordinates in format \&#39;lon;lat\&#39; (longitude;latitude), e.g., \&#39;2.37705;48.84675\&#39;
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public coordsCoordGet(coord: string, options?: RawAxiosRequestConfig) {
        return InvertedGeocodingApiFp(this.configuration).coordsCoordGet(coord, options).then((request) => request(this.axios, this.basePath));
    }
}

