/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Line } from './line';
// May contain unused imports in some cases
// @ts-ignore
import type { Network } from './network';

export interface CoverageCoverageTrafficReportsGet200ResponseTrafficReportsInner {
    'network'?: Network;
    'lines'?: Array<Line>;
    'pt_objects'?: Array<object>;
}

