/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CoverageCoverageTrafficReportsGet200ResponseTrafficReportsInner } from './coverage-coverage-traffic-reports-get200-response-traffic-reports-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { Disruption } from './disruption';
// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';

export interface CoverageCoverageTrafficReportsGet200Response {
    'traffic_reports'?: Array<CoverageCoverageTrafficReportsGet200ResponseTrafficReportsInner>;
    'disruptions'?: Array<Disruption>;
    'links'?: Array<Link>;
}

