/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DateTime {
    /**
     * Date and time (YYYYMMDDTHHmmss)
     */
    'date_time'?: string;
    /**
     * Base date and time (YYYYMMDDTHHmmss)
     */
    'base_date_time'?: string;
    /**
     * Data freshness
     */
    'data_freshness'?: DateTimeDataFreshnessEnum;
}

export const DateTimeDataFreshnessEnum = {
    BaseSchedule: 'base_schedule',
    Realtime: 'realtime'
} as const;

export type DateTimeDataFreshnessEnum = typeof DateTimeDataFreshnessEnum[keyof typeof DateTimeDataFreshnessEnum];


