/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DisruptionMessagesInner } from './disruption-messages-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { Impact } from './impact';
// May contain unused imports in some cases
// @ts-ignore
import type { ImpactApplicationPeriodsInner } from './impact-application-periods-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { Severity } from './severity';

export interface Disruption {
    /**
     * Disruption ID
     */
    'id'?: string;
    /**
     * Disruption ID
     */
    'disruption_id'?: string;
    /**
     * Disruption URI
     */
    'disruption_uri'?: string;
    'severity'?: Severity;
    /**
     * Impact ID
     */
    'impact_id'?: string;
    'application_periods'?: Array<ImpactApplicationPeriodsInner>;
    'messages'?: Array<DisruptionMessagesInner>;
    'impacted_objects'?: Array<Impact>;
    /**
     * Disruption cause
     */
    'cause'?: string;
    /**
     * Disruption category
     */
    'category'?: string;
}

