/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Coord } from './coord';
// May contain unused imports in some cases
// @ts-ignore
import type { GeocodeAdministrativeRegionsInner } from './geocode-administrative-regions-inner';

export interface Geocode {
    /**
     * Address name
     */
    'name'?: string;
    /**
     * Full address label
     */
    'label'?: string;
    /**
     * Address ID
     */
    'id'?: string;
    /**
     * Address type
     */
    'type'?: string;
    'coord'?: Coord;
    /**
     * House number
     */
    'house_number'?: string;
    /**
     * Street name
     */
    'street'?: string;
    /**
     * List of administrative regions
     */
    'administrative_regions'?: Array<GeocodeAdministrativeRegionsInner>;
}

