/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ImpactPtObjectTrip } from './impact-pt-object-trip';

/**
 * Affected PT object
 */
export interface ImpactPtObject {
    /**
     * PT object ID
     */
    'id'?: string;
    /**
     * PT object name
     */
    'name'?: string;
    /**
     * PT object quality indicator
     */
    'quality'?: number;
    'trip'?: ImpactPtObjectTrip;
    /**
     * Embedded object type
     */
    'embedded_type'?: ImpactPtObjectEmbeddedTypeEnum;
}

export const ImpactPtObjectEmbeddedTypeEnum = {
    VehicleJourney: 'vehicle_journey',
    Trip: 'trip',
    Route: 'route',
    Line: 'line',
    StopPoint: 'stop_point',
    StopArea: 'stop_area'
} as const;

export type ImpactPtObjectEmbeddedTypeEnum = typeof ImpactPtObjectEmbeddedTypeEnum[keyof typeof ImpactPtObjectEmbeddedTypeEnum];


