/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface JourneyItemDurations {
    /**
     * Total duration in seconds
     */
    'total'?: number;
    /**
     * Walking duration in seconds
     */
    'walking'?: number;
    /**
     * Bike duration in seconds
     */
    'bike'?: number;
    /**
     * Car duration in seconds
     */
    'car'?: number;
    /**
     * Ridesharing duration in seconds
     */
    'ridesharing'?: number;
    /**
     * Taxi duration in seconds
     */
    'taxi'?: number;
}

