/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Disruption } from './disruption';
// May contain unused imports in some cases
// @ts-ignore
import type { JourneyContext } from './journey-context';
// May contain unused imports in some cases
// @ts-ignore
import type { JourneyItem } from './journey-item';
// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';

export interface Journey {
    'journeys'?: Array<JourneyItem>;
    'disruptions'?: Array<Disruption>;
    'links'?: Array<Link>;
    'feed_publishers'?: Array<object>;
    'context'?: JourneyContext;
}

