/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AirPollutants } from './air-pollutants';
// May contain unused imports in some cases
// @ts-ignore
import type { Co2Emission } from './co2-emission';
// May contain unused imports in some cases
// @ts-ignore
import type { Fare } from './fare';
// May contain unused imports in some cases
// @ts-ignore
import type { JourneyCalendar } from './journey-calendar';
// May contain unused imports in some cases
// @ts-ignore
import type { JourneyDistances } from './journey-distances';
// May contain unused imports in some cases
// @ts-ignore
import type { JourneyItemDurations } from './journey-item-durations';
// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';
// May contain unused imports in some cases
// @ts-ignore
import type { Section } from './section';

export interface JourneyItem {
    'durations'?: JourneyItemDurations;
    /**
     * Total duration in seconds (deprecated, use durations.total)
     */
    'duration'?: number;
    /**
     * Number of transfers
     */
    'nb_transfers'?: number;
    /**
     * Departure date time (YYYYMMDDTHHmmss)
     */
    'departure_date_time'?: string;
    /**
     * Arrival date time (YYYYMMDDTHHmmss)
     */
    'arrival_date_time'?: string;
    /**
     * Requested date time (YYYYMMDDTHHmmss)
     */
    'requested_date_time'?: string;
    /**
     * List of sections in the journey
     */
    'sections'?: Array<Section>;
    /**
     * Journey type
     */
    'type'?: string;
    /**
     * Journey status
     */
    'status'?: string;
    /**
     * Journey tags
     */
    'tags'?: Array<string>;
    'co2_emission'?: Co2Emission;
    'air_pollutants'?: AirPollutants;
    'distances'?: JourneyDistances;
    'fare'?: Fare;
    'calendars'?: Array<JourneyCalendar>;
    'links'?: Array<Link>;
}

