/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Pagination {
    /**
     * Start page number
     */
    'start_page'?: number;
    /**
     * Items on current page
     */
    'items_on_page'?: number;
    /**
     * Items per page
     */
    'items_per_page'?: number;
    /**
     * Total number of results
     */
    'total_result'?: number;
}

