/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DisplayInformation } from './display-information';
// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';
// May contain unused imports in some cases
// @ts-ignore
import type { Place } from './place';
// May contain unused imports in some cases
// @ts-ignore
import type { Route } from './route';
// May contain unused imports in some cases
// @ts-ignore
import type { SectionStopDateTimesInner } from './section-stop-date-times-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { SectionTrip } from './section-trip';
// May contain unused imports in some cases
// @ts-ignore
import type { SectionVehicleJourney } from './section-vehicle-journey';

export interface Section {
    /**
     * Section ID
     */
    'id'?: string;
    /**
     * Section type
     */
    'type'?: SectionTypeEnum;
    'from'?: Place;
    'to'?: Place;
    /**
     * Duration in seconds
     */
    'duration'?: number;
    /**
     * Departure date time (YYYYMMDDTHHmmss)
     */
    'departure_date_time'?: string;
    /**
     * Arrival date time (YYYYMMDDTHHmmss)
     */
    'arrival_date_time'?: string;
    /**
     * Base departure date time (YYYYMMDDTHHmmss)
     */
    'base_departure_date_time'?: string;
    /**
     * Base arrival date time (YYYYMMDDTHHmmss)
     */
    'base_arrival_date_time'?: string;
    /**
     * GeoJSON geometry
     */
    'geojson'?: object;
    /**
     * Transport mode
     */
    'mode'?: string;
    /**
     * Transfer type
     */
    'transfer_type'?: string;
    'display_informations'?: DisplayInformation;
    'vehicle_journey'?: SectionVehicleJourney;
    'trip'?: SectionTrip;
    'route'?: Route;
    /**
     * List of stop times for this section
     */
    'stop_date_times'?: Array<SectionStopDateTimesInner>;
    'links'?: Array<Link>;
}

export const SectionTypeEnum = {
    PublicTransport: 'public_transport',
    StreetNetwork: 'street_network',
    Transfer: 'transfer',
    Waiting: 'waiting',
    Boarding: 'boarding',
    Alighting: 'alighting'
} as const;

export type SectionTypeEnum = typeof SectionTypeEnum[keyof typeof SectionTypeEnum];


