/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Severity {
    /**
     * Severity name
     */
    'name'?: string;
    /**
     * Severity color
     */
    'color'?: string;
    /**
     * Severity priority
     */
    'priority'?: number;
    /**
     * Effect type
     */
    'effect'?: SeverityEffectEnum;
}

export const SeverityEffectEnum = {
    NoService: 'NO_SERVICE',
    ReducedService: 'REDUCED_SERVICE',
    SignificantDelays: 'SIGNIFICANT_DELAYS',
    Detour: 'DETOUR',
    AdditionalService: 'ADDITIONAL_SERVICE',
    ModifiedService: 'MODIFIED_SERVICE',
    OtherEffect: 'OTHER_EFFECT',
    UnknownEffect: 'UNKNOWN_EFFECT',
    StopMoved: 'STOP_MOVED',
    NoEffect: 'NO_EFFECT'
} as const;

export type SeverityEffectEnum = typeof SeverityEffectEnum[keyof typeof SeverityEffectEnum];


