/* tslint:disable */
/* eslint-disable */
/**
 * Navitia API - SNCF
 * Complete API documentation for Navitia/SNCF public transportation API. Based on https://doc.navitia.io
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Coord } from './coord';
// May contain unused imports in some cases
// @ts-ignore
import type { Link } from './link';
// May contain unused imports in some cases
// @ts-ignore
import type { StopArea } from './stop-area';

export interface StopPoint {
    /**
     * Stop point ID
     */
    'id'?: string;
    /**
     * Stop point name
     */
    'name'?: string;
    'coord'?: Coord;
    'stop_area'?: StopArea;
    'links'?: Array<Link>;
}

